framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    trusted_hosts: ~
    session:
        handler_id: ~
    esi: { enabled: true }
    fragments: { enabled: true }
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.root_dir%/../public/build/manifest.json'
    cache:
        prefix_seed: hiberbee
    ide: ~
    router:
        strict_requirements: ~
