framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    trusted_hosts: ~
    session:
        handler_id: ~
    esi: { enabled: true }
    fragments: { enabled: true }
    php_errors:
        log: true
    cache:
        prefix_seed: hiberbee
    ide: ~
    router:
        strict_requirements: ~
