security:
    encoders:
        App\Entity\Account:
            algorithm: bcrypt
    providers:
        db:
            entity:
                class: App\Entity\Account
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: db
            logout:
                path:   /logout
                target: /
                invalidate_session: false
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }