security:
    encoders:
        App\Entity\Account:
            algorithm: bcrypt
            cost: 12
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }