version: '3.4'

services:
  db:
    image: percona
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: hiberbee

  backend:
    image: hiberbee/hiberbee.com
    container_name: backend
    depends_on:
      - db
    links:
      - db
    volumes:
      - document_root:/var/www/hiberbee.com/public
      - nginx_configuration:/var/www/hiberbee.com/etc/nginx
      - backend_socket:/run/php:rw

  web:
    image: nginx
    container_name: web
    depends_on:
      - backend
    ports:
       - 80:80
    volumes:
      - document_root:/var/www/hiberbee.com/public:ro
      - nginx_configuration:/var/www/hiberbee.com/etc/nginx:ro
      - backend_socket:/run/php:rw
    command: /bin/bash -c "cp /var/www/hiberbee.com/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  db-data:
  document_root:
  backend_socket:
  nginx_configuration: