version: '3.4'

services:
  app:
    image: hiberbee/hiberbee.com
    container_name: app
    volumes:
      - document_root:/var/www/hiberbee.com/public
      - nginx_configuration:/var/www/hiberbee.com/etc/nginx
      - backend_socket:/run/php
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_SECRET: ${APP_SECRET}

  web:
    image: nginx
    container_name: web
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - document_root:/var/www/hiberbee.com/public:ro
      - nginx_configuration:/var/www/hiberbee.com/etc/nginx:ro
      - backend_socket:/run/php:ro
      - ./ssl:/root/ssl
    command: /bin/bash -c "cp /var/www/hiberbee.com/etc/nginx/conf.d/production.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  document_root:
  backend_socket:
  nginx_configuration: