version: '3.4'

services:
  db:
    image: percona
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

  backend:
    build:
      context: .
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: backend
    depends_on:
      - db
    links:
      - db
    ports:
      - 9000:9000
    volumes:
      - code:/var/www/hiberbee.com

  web:
    image: nginx
    container_name: web
    depends_on:
      - backend
    ports:
       - 80:80
    volumes:
      - code:/var/www/hiberbee.com
    command: /bin/bash -c "cp /var/www/hiberbee.com/etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  db-data:
  code: