version: '3.4'

services:
  db:
    image: percona
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

  backend:
    build:
      context: etc/app
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: backend
    depends_on:
      - db
    volumes:
      - ${CODE_VOLUME_MOUNT}
    links:
      - db
    ports:
      - 9000:9000
    working_dir: ${WORKING_DIR}
    command: composer install

  web:
    image: nginx
    container_name: web
    depends_on:
      - backend
    ports:
       - 80:80
    volumes:
      - ${CODE_VOLUME_MOUNT}
    command: /bin/bash -c "cp $WORKING_DIR/etc/web/default.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  frontend:
    image: node
    container_name: frontend
    volumes:
      - ${CODE_VOLUME_MOUNT}
    tty: true
    working_dir: ${WORKING_DIR}
    command: yarn dev

volumes:
  db-data:
