version: '3.4'

services:
  app:
    image: hiberbee/docker.symfony
    volumes:
      - .:/var/www/hiberbee.com:rw
      - backend_socket:/run/php:rw
    depends_on:
      - db
    working_dir: /var/www/hiberbee.com
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: 'secret'
      DATABASE_URL: 'postgres://hiberbee:password@db:5432/`hiberbee'

  web:
    image: hiberbee/docker.nginx
    depends_on:
      - app
    ports:
       - 80:80
       - 443:443
       - 1234:1234
    volumes:
      - .:/var/www/localhost:rw
      - backend_socket:/run/php:rw
    command: /bin/bash -c "envsubst '$${SERVER_NAME}' < /etc/nginx/hosts/symfony.template > /etc/nginx/hosts/default.conf && nginx -g 'daemon off;'"
    environment:
      SERVER_NAME: localhost

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: hiberbee
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hiberbee
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  backend_socket:
  db_data: