version: '3.4'

services:
  app:
    image: hiberbee/hiberbee.com
    container_name: app
    depends_on:
      - db
    volumes:
      - document_root:/var/www/hiberbee.com/public
      - nginx_configuration:/var/www/hiberbee.com/etc/nginx
      - backend_socket:/run/php
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}

  web:
    image: hiberbee/docker.nginx
    container_name: web
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - document_root:/var/www/hiberbee.com/public:ro
      - nginx_configuration:/var/www/hiberbee.com/etc/nginx:ro
      - backend_socket:/run/php:ro
      - ./ssl:/etc/ssl
    command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/hosts/symfony.template > /etc/nginx/hosts/default.conf && nginx -g 'daemon off;'"
    environment:
      SERVER_NAME: production

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
  document_root:
  backend_socket:
  nginx_configuration: