version: '3.4'

services:
  db:
    image: percona
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}

  backend:
    build:
      context: etc/app
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: backend
    depends_on:
      - db
    volumes:
      - ${PROJECT_LOCAL_PATH}:${PROJECT_REMOTE_PATH}:rw
    links:
      - db
    ports:
      - 9000:9000

  web:
    image: nginx
    container_name: web
    depends_on:
      - backend
    ports:
       - 80:80
    volumes:
      - ${PROJECT_LOCAL_PATH}:${PROJECT_REMOTE_PATH}:rw
    environment:
      - PROJECT_REMOTE_PATH=${PROJECT_REMOTE_PATH}
    command: /bin/bash -c "cp $PROJECT_REMOTE_PATH/etc/web/default.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  frontend:
    image: node
    container_name: frontend
    volumes:
      - ${PROJECT_LOCAL_PATH}:${PROJECT_REMOTE_PATH}:rw
    tty: true

volumes:
  db-data:
